#ifndef _CONFIG_H
#define _CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 800

#define AGENT_MAX_SPEED 0.028
#define AGENT_MAX_SPEED_LIMIT sqrt(2*(AGENT_MAX_SPEED*AGENT_MAX_SPEED))
#define MAX_ATTRACK_FORCE 0.001
#define MAX_ACTRACK_FORCE 100
#define MAX_ACTRACK_FORCE_LIMIT 0.001

#endif
